const I18N={};
I18N.fr={_adj:['Cobalt','Fulgurant','Pourpre','Stellaire','Vif','Polaire','Ardent','Lunaire','Électrique','Sombre','Radieux','Quantique'],_noun:['Hexagone','Prisme','Pentagone','Comète','Spirale','Vecteur','Nova','Pulsar','Octogone','Photon','Orbite','Fractale'],_days:['dimanche','lundi','mardi','mercredi','jeudi','vendredi','samedi'],_units:['k','M','Md','Bn'],_dur:['s','min','h','j'],name_short:'3 caractères minimum.',name_long:'16 caractères maximum.',name_cost:'Il te faut {n} gemmes.'};
I18N.en={_adj:['Cobalt','Blazing','Crimson','Stellar','Swift','Polar','Fiery','Lunar','Electric','Shadow','Radiant','Quantum'],_noun:['Hexagon','Prism','Pentagon','Comet','Spiral','Vector','Nova','Pulsar','Octagon','Photon','Orbit','Fractal'],_days:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],_units:['K','M','B','T'],_dur:['s','min','h','d'],name_short:'3 characters minimum.',name_long:'16 characters maximum.',name_cost:'You need {n} gems.'};
I18N.es={_adj:['Cobalto','Fulgurante','Púrpura','Estelar','Veloz','Polar','Ardiente','Lunar','Eléctrico','Sombrío','Radiante','Cuántico'],_noun:['Hexágono','Prisma','Pentágono','Cometa','Espiral','Vector','Nova','Púlsar','Octógono','Fotón','Órbita','Fractal'],_days:['domingo','lunes','martes','miércoles','jueves','viernes','sábado'],_units:['k','M','MM','B'],_dur:['s','min','h','d'],name_short:'3 caracteres como mínimo.',name_long:'16 caracteres como máximo.',name_cost:'Necesitas {n} gemas.'};
I18N.de={_adj:['Kobalt','Blitzend','Purpur','Stellar','Flink','Polar','Glühend','Lunar','Elektrisch','Dunkel','Strahlend','Quanten'],_noun:['Sechseck','Prisma','Fünfeck','Komet','Spirale','Vektor','Nova','Pulsar','Achteck','Photon','Orbit','Fraktal'],_days:['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],_units:['Tsd.','Mio.','Mrd.','Bio.'],_dur:['s','Min.','Std.','T.'],name_short:'Mindestens 3 Zeichen.',name_long:'Höchstens 16 Zeichen.',name_cost:'Du brauchst {n} Edelsteine.'};
I18N.pt={_adj:['Cobalto','Fulgurante','Púrpura','Estelar','Veloz','Polar','Ardente','Lunar','Elétrico','Sombrio','Radiante','Quântico'],_noun:['Hexágono','Prisma','Pentágono','Cometa','Espiral','Vetor','Nova','Pulsar','Octógono','Fotão','Órbita','Fractal'],_days:['domingo','segunda','terça','quarta','quinta','sexta','sábado'],_units:['mil','mi','bi','tri'],_dur:['s','min','h','d'],name_short:'Mínimo de 3 caracteres.',name_long:'Máximo de 16 caracteres.',name_cost:'Precisas de {n} gemas.'};
I18N.it={_adj:['Cobalto','Fulminante','Purpureo','Stellare','Vivace','Polare','Ardente','Lunare','Elettrico','Oscuro','Radioso','Quantico'],_noun:['Esagono','Prisma','Pentagono','Cometa','Spirale','Vettore','Nova','Pulsar','Ottagono','Fotone','Orbita','Frattale'],_days:['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'],_units:['k','M','Mrd','Bln'],_dur:['s','min','h','g'],name_short:'Minimo 3 caratteri.',name_long:'Massimo 16 caratteri.',name_cost:'Ti servono {n} gemme.'};
let LANG='fr';
const LANG_LIST=()=>Object.keys(I18N);
function pickLang(){try{const s=localStorage.getItem('prisme-lang');if(s&&I18N[s])return s;}catch(e){}const nav=(navigator.languages||[navigator.language||'fr']).map(x=>x.slice(0,2).toLowerCase());for(const l of nav)if(I18N[l])return l;return 'en';}
function setLang(l){if(!I18N[l])return;LANG=l;try{localStorage.setItem('prisme-lang',l);}catch(e){}}
/* t('clé',{n:3}) : remplace {n} ; {n|s} ajoute « s » si n>1 (ou la chaîne donnée) */
function t(k,v){let s=I18N[LANG][k];if(s==null)s=I18N.fr[k];if(s==null)return k;if(!v)return s;return s.replace(/\{(\w+)(?:\|([^}]*))?\}/g,(m,key,pl)=>{const val=v[key];if(pl!==undefined){const many=+String(val).replace(/[^\d.]/g,'')>1;if(pl.includes('/')){const [a,b]=pl.split('/');return many?b:a;}return many?pl:'';}return val==null?'':String(val);});}
/* nombres : séparateurs de la langue, décimales locales */
const dec=(v,d=1)=>{try{return new Intl.NumberFormat(LANG,{minimumFractionDigits:0,maximumFractionDigits:d}).format(+v.toFixed(d));}catch(e){return v.toFixed(d);}};
const grp=n=>{try{return new Intl.NumberFormat(LANG).format(n);}catch(e){return String(n);}};
